//! Browser fingerprinting and header-completeness scoring.
//!
//! Real browsers send a predictable set of headers (Accept, Accept-Language,
//! Accept-Encoding, sec-fetch-*, sec-ch-ua-* on Chromium, …). DDoS toolkits
//! and naive HTTP clients almost always omit these or send inconsistent
//! combinations.
//!
//! Each missing or inconsistent signal contributes a small score; the totals
//! are designed to add up to "challenge" territory for clearly-fake clients
//! while leaving real browsers alone.

use crate::request::RequestCtx;
use crate::decision::DecisionReason;

const W_NO_ACCEPT:           u32 = 8;
const W_NO_ACCEPT_LANG:      u32 = 8;
const W_NO_ACCEPT_ENCODING:  u32 = 10;
const W_NO_SEC_FETCH:        u32 = 12;
const W_UA_SECCH_MISMATCH:   u32 = 35;
const W_HTTP_1_0:            u32 = 25;
const W_TINY_UA:             u32 = 25;
const W_NUMERIC_UA:          u32 = 30;
const W_NO_REFERER_POST:     u32 = 12;
const W_HEADERLESS_BROWSER:  u32 = 30;

pub fn score(ctx: &RequestCtx) -> Vec<DecisionReason> {
    let mut out = Vec::new();
    let ua = ctx.user_agent.to_ascii_lowercase();
    let claims_chromium = ua.contains("chrome/") || ua.contains("edg/") || ua.contains("opr/");
    let claims_browser  = ua.contains("mozilla/") || claims_chromium || ua.contains("firefox/") || ua.contains("safari/");

    // --- core RFC niceties every browser sends ---
    if !ctx.headers.contains_key("accept") {
        out.push(reason("BOT-NO-ACCEPT", "bot", W_NO_ACCEPT, "Accept header missing"));
    }
    if !ctx.headers.contains_key("accept-language") {
        out.push(reason("BOT-NO-LANG", "bot", W_NO_ACCEPT_LANG, "Accept-Language header missing"));
    }
    if !ctx.headers.contains_key("accept-encoding") {
        out.push(reason("BOT-NO-ENC", "bot", W_NO_ACCEPT_ENCODING, "Accept-Encoding header missing"));
    }

    // --- fetch metadata (modern browsers send these on every navigation) ---
    let has_sec_fetch = ctx.headers.keys().any(|k| k.starts_with("sec-fetch-"));
    if claims_browser && !has_sec_fetch {
        out.push(reason("BOT-NO-SEC-FETCH", "bot", W_NO_SEC_FETCH,
            "claims browser UA but no sec-fetch-* headers"));
    }

    // --- Chromium UA without sec-ch-ua → impossible for a real Chromium ≥89 ---
    if claims_chromium && !ctx.headers.contains_key("sec-ch-ua") {
        out.push(reason("BOT-UA-MISMATCH", "bot", W_UA_SECCH_MISMATCH,
            "Chrome UA without sec-ch-ua header"));
    }

    // --- HTTP/1.0 from public internet is overwhelmingly attack tooling ---
    // We can't know the version cheaply through Pingora's session here, so we
    // surface it via headers["x-http-version"] if the proxy stamps it (best effort).
    if let Some(v) = ctx.headers.get("x-http-version") {
        if v == "HTTP/1.0" || v == "1.0" {
            out.push(reason("BOT-HTTP10", "bot", W_HTTP_1_0,
                "HTTP/1.0 from public internet"));
        }
    }

    // --- UA shape anomalies ---
    if !ctx.user_agent.is_empty() {
        if ctx.user_agent.len() < 8 {
            out.push(reason("BOT-UA-TINY", "bot", W_TINY_UA,
                "User-Agent suspiciously short"));
        }
        // Pure-numeric/space UA — common in flood scripts.
        if ctx.user_agent.chars().all(|c| c.is_ascii_digit() || c.is_ascii_whitespace()) {
            out.push(reason("BOT-UA-NUMERIC", "bot", W_NUMERIC_UA,
                "User-Agent looks autogenerated"));
        }
    }

    // --- Browser claim with too few headers is a fingerprint giveaway ---
    if claims_browser && ctx.headers.len() < 6 {
        out.push(reason("BOT-MIN-HDRS", "bot", W_HEADERLESS_BROWSER,
            "browser UA with very few headers"));
    }

    // --- POST without Referer to non-API path is a classic CSRF/flood marker ---
    if ctx.method.eq_ignore_ascii_case("POST")
        && !ctx.headers.contains_key("referer")
        && !ctx.path.starts_with("/api/")
    {
        out.push(reason("BOT-NO-REFERER-POST", "bot", W_NO_REFERER_POST,
            "POST without Referer outside /api/"));
    }

    out
}

fn reason(rule: &'static str, cat: &'static str, score: u32, detail: &str) -> DecisionReason {
    DecisionReason { rule_id: rule.to_string(), category: cat.to_string(), score, detail: detail.to_string() }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use std::net::IpAddr;

    fn ctx_with(headers: &[(&str, &str)], ua: &str, method: &str, path: &str) -> RequestCtx {
        let mut h = HashMap::new();
        for (k, v) in headers { h.insert(k.to_string(), v.to_string()); }
        RequestCtx {
            request_id: "t".into(),
            client_ip: IpAddr::from([1,2,3,4]),
            method: method.into(), uri: path.into(), path: path.into(),
            query: "".into(), host: "h".into(), user_agent: ua.into(),
            headers: h, cookies: HashMap::new(),
            http_version: "HTTP/1.1".into(), header_order: vec![], cookie_order: vec![], body_preview: vec![], content_length: None, country: None, ja4h: String::new(), ja3: String::new(), ja4: String::new(),
        }
    }

    #[test]
    fn real_chrome_passes_clean() {
        let r = score(&ctx_with(&[
            ("accept", "text/html,*/*;q=0.8"),
            ("accept-language", "en-US,en;q=0.9"),
            ("accept-encoding", "gzip, deflate, br"),
            ("sec-fetch-dest", "document"),
            ("sec-fetch-mode", "navigate"),
            ("sec-ch-ua", "\"Chromium\";v=\"123\""),
            ("user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"),
        ], "Mozilla/5.0 (X11) Chrome/123.0.0.0", "GET", "/"));
        assert!(r.is_empty(), "real chrome should pass clean: got {:?}", r);
    }

    #[test]
    fn fake_chrome_no_sec_ch_ua() {
        let r = score(&ctx_with(&[
            ("user-agent", "Mozilla/5.0 Chrome/120.0.0.0"),
        ], "Mozilla/5.0 Chrome/120.0.0.0", "GET", "/"));
        let total: u32 = r.iter().map(|x| x.score).sum();
        assert!(total >= 35, "expected high score for fake chrome: {}", total);
    }

    #[test]
    fn naked_post_caught() {
        let r = score(&ctx_with(&[("user-agent", "anything")], "anything", "POST", "/login"));
        assert!(r.iter().any(|x| x.rule_id == "BOT-NO-REFERER-POST"));
    }
}
